language: node_js
node_js:
  - "10"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test -- --coverage
before_deploy:
  - npm run build
deploy:
  provider: firebase
  project: code-chat-cat
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: staging
  skip_cleanup: true
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
